version: "3.8"

services:
  proftpd:
    container_name: proftpd
    build:
      context: ./docker/proftpd/
    command: ["proftpd", "-n"]
    ports:
      - "20:20"
      - "21:21"
    volumes:
      - ./proftpd/proftpd.conf:/etc/proftpd/proftpd.conf
