version: "3.8"

services:
  proftpd:
    build:
      context: .
    command: ["proftpd", "-n"]
    ports:
      - "20:20"
      - "21:21"
    volumes:
      - ./proftpd/proftpd.conf:/etc/proftpd/proftpd.conf
